#!/bin/bash
#
# Git Cleanup Script
# Removes files that should be gitignored from git history

set -e  # Exit on error

echo "=== Git Cleanup Script ==="
echo "This will remove user-specific files from git tracking"
echo ""

# 1. Remove .DS_Store files (macOS metadata)
echo "Step 1: Removing .DS_Store files..."
find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch

# 2. Remove xcuserstate files (Xcode user state)
echo "Step 2: Removing xcuserstate files..."
find . -name "*.xcuserstate" -print0 | xargs -0 git rm -f --ignore-unmatch

# 3. Remove xcuserdata directories (Xcode user data)
echo "Step 3: Removing xcuserdata directories..."
git rm -rf --ignore-unmatch **/xcuserdata

# 4. Remove xcschemes (user-specific Xcode schemes)
echo "Step 4: Removing xcschemes management files..."
find . -name "xcschememanagement.plist" -print0 | xargs -0 git rm -f --ignore-unmatch

# 5. Remove any .env files if accidentally committed
echo "Step 5: Checking for .env files..."
git rm -f --ignore-unmatch .env
git rm -f --ignore-unmatch .env.local

# 6. Remove local xcconfig overrides
echo "Step 6: Removing local xcconfig overrides..."
git rm -f --ignore-unmatch Configuration/Development.xcconfig

# 7. Remove .build directories (Swift Package Manager build artifacts)
echo "Step 7: Removing .build directories..."
git rm -rf --ignore-unmatch EulumdatApp/.build
git rm -rf --ignore-unmatch swift/.build
git rm -rf --ignore-unmatch .build

# 8. Remove XCFramework build artifacts
echo "Step 8: Removing XCFramework headers (will be regenerated)..."
git rm -rf --ignore-unmatch swift/eulumdat_ffiFFI.xcframework

# 9. Remove UITest directories (generated by Xcode)
echo "Step 9: Removing UITests directories..."
git rm -rf --ignore-unmatch EulumdatApp/EulumdatAppUITests

echo ""
echo "=== Cleanup Complete ==="
echo "Files removed from git tracking (but still on disk)"
echo ""
echo "Next steps:"
echo "1. Review changes: git status"
echo "2. Commit: git commit -m '[FIX] Remove user-specific files from git tracking'"
echo "3. Push: git push origin mac/ios-app"
echo ""
echo "Note: These files are now in .gitignore and won't be tracked in future commits"
