use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 10001,
            category: Category::BimIntegration,
            difficulty: Difficulty::Beginner,
            text: "What does BIM stand for?".into(),
            options: vec!["Building Information Modeling".into(), "Built-In Measurement".into(), "Brightness Integration Method".into(), "Beam Intensity Mapping".into()],
            correct_index: 0,
            explanation: "BIM stands for Building Information Modeling, a process for creating and managing digital representations of buildings.".into(),
            reference: Some("ISO 19650".into()),
        },
        Question {
            id: 10002,
            category: Category::BimIntegration,
            difficulty: Difficulty::Intermediate,
            text: "What standard defines BIM parameters for lighting products?".into(),
            options: vec!["ISO 19650".into(), "ANSI/IES TM-32-24".into(), "CIE 117:1995".into(), "EN 12464-1".into()],
            correct_index: 1,
            explanation: "ANSI/IES TM-32-24 defines standard parameters for representing lighting products in BIM environments.".into(),
            reference: Some("ANSI/IES TM-32-24".into()),
        },
        Question {
            id: 10003,
            category: Category::BimIntegration,
            difficulty: Difficulty::Intermediate,
            text: "What two housing shapes does TM-32-24 define for luminaire geometry?".into(),
            options: vec![
                "Sphere and cone".into(),
                "Cuboid and cylinder".into(),
                "Rectangle and circle".into(),
                "Box and tube".into(),
            ],
            correct_index: 1,
            explanation: "TM-32-24 defines two simplified housing shapes: cuboid (rectangular box) and cylinder for BIM representation.".into(),
            reference: Some("ANSI/IES TM-32-24".into()),
        },
        Question {
            id: 10004,
            category: Category::BimIntegration,
            difficulty: Difficulty::Intermediate,
            text: "What identifier system does TM-32-24 use for luminaire classification?".into(),
            options: vec![
                "UPC barcodes".into(),
                "NEMA GUIDs (Globally Unique Identifiers)".into(),
                "ISO product codes".into(),
                "EAN numbers".into(),
            ],
            correct_index: 1,
            explanation: "TM-32-24 uses NEMA GUIDs for unique product identification in BIM systems.".into(),
            reference: Some("ANSI/IES TM-32-24".into()),
        },
        Question {
            id: 10005,
            category: Category::BimIntegration,
            difficulty: Difficulty::Expert,
            text: "What is the melanopic factor used for in TM-32-24?".into(),
            options: vec![
                "Measuring lamp lifetime".into(),
                "Circadian rhythm impact assessment (melatonin suppression)".into(),
                "Determining color rendering quality".into(),
                "Calculating energy efficiency".into(),
            ],
            correct_index: 1,
            explanation: "The melanopic factor quantifies a light source's impact on circadian rhythm by measuring its potential to suppress melatonin production via intrinsically photosensitive retinal ganglion cells (ipRGCs).".into(),
            reference: Some("ANSI/IES TM-32-24, CIE S 026:2018".into()),
        },
        Question {
            id: 10006,
            category: Category::BimIntegration,
            difficulty: Difficulty::Expert,
            text: "What file format does TM-32-24 use for BIM data exchange?".into(),
            options: vec!["JSON".into(), "XML".into(), "CSV".into(), "IFC".into()],
            correct_index: 1,
            explanation: "TM-32-24 uses XML for structured data exchange of luminaire parameters in BIM environments.".into(),
            reference: Some("ANSI/IES TM-32-24".into()),
        },
        Question {
            id: 10007,
            category: Category::BimIntegration,
            difficulty: Difficulty::Beginner,
            text: "Why is BIM integration important for lighting design?".into(),
            options: vec![
                "It makes lights brighter".into(),
                "It allows coordinated design with architectural and MEP systems".into(),
                "It reduces electricity consumption".into(),
                "It is required by law in all countries".into(),
            ],
            correct_index: 1,
            explanation: "BIM integration allows lighting designers to coordinate with architecture, structural, and MEP (mechanical, electrical, plumbing) systems in a shared digital model.".into(),
            reference: Some("ISO 19650".into()),
        },
        Question {
            id: 10008,
            category: Category::BimIntegration,
            difficulty: Difficulty::Expert,
            text: "What mounting types does TM-32-24 define?".into(),
            options: vec![
                "Wall and ceiling only".into(),
                "Recessed, surface, suspended, floor, wall, track, and freestanding".into(),
                "Indoor and outdoor".into(),
                "Fixed and adjustable".into(),
            ],
            correct_index: 1,
            explanation: "TM-32-24 defines multiple mounting types including recessed, surface, suspended, floor, wall, track, and freestanding to cover all installation scenarios.".into(),
            reference: Some("ANSI/IES TM-32-24".into()),
        },
    ]
}
