use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 6001,
            category: Category::BugRating,
            difficulty: Difficulty::Beginner,
            text: "What does BUG stand for in lighting?".into(),
            options: vec!["Brightness Under Glass".into(), "Backlight, Uplight, Glare".into(), "Beam Uniformity Grade".into(), "Brightness Utilization Guide".into()],
            correct_index: 1,
            explanation: "BUG stands for Backlight, Uplight, Glare — three categories of undesirable light output from outdoor luminaires.".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6002,
            category: Category::BugRating,
            difficulty: Difficulty::Beginner,
            text: "What standard defines BUG ratings?".into(),
            options: vec!["CIE 150:2017".into(), "EN 13201".into(), "IESNA TM-15-11".into(), "IDA 530".into()],
            correct_index: 2,
            explanation: "BUG ratings are defined by IESNA TM-15-11 (Luminaire Classification System for Outdoor Luminaires).".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6003,
            category: Category::BugRating,
            difficulty: Difficulty::Beginner,
            text: "Is a lower or higher BUG rating better for reducing light pollution?".into(),
            options: vec!["Higher is better".into(), "Lower is better (B0-U0-G0 is best)".into(), "It depends on the application".into(), "BUG ratings don't relate to light pollution".into()],
            correct_index: 1,
            explanation: "Lower BUG ratings indicate less wasted/unwanted light. B0-U0-G0 is the ideal rating with minimal backlight, uplight, and glare.".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6004,
            category: Category::BugRating,
            difficulty: Difficulty::Intermediate,
            text: "What angle range (from nadir) defines the Uplight zone?".into(),
            options: vec!["0-30°".into(), "60-80°".into(), "80-90°".into(), "90-180° (above horizontal)".into()],
            correct_index: 3,
            explanation: "Uplight is all light emitted above the horizontal plane (gamma 90-180°), subdivided into UL (90-100°) and UH (100-180°).".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6005,
            category: Category::BugRating,
            difficulty: Difficulty::Intermediate,
            text: "What range does the BUG scale use for each component?".into(),
            options: vec!["0 to 3".into(), "0 to 5".into(), "0 to 10".into(), "1 to 5".into()],
            correct_index: 1,
            explanation: "Each BUG component (B, U, G) is rated on a scale of 0 to 5, where 0 is best (least pollution) and 5 is worst.".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6006,
            category: Category::BugRating,
            difficulty: Difficulty::Intermediate,
            text: "What compliance programs use BUG ratings?".into(),
            options: vec![
                "Only IDA Dark Sky".into(),
                "IDA/IES MLO, LEED v4, California Title 24".into(),
                "Only LEED certification".into(),
                "Only European EN standards".into(),
            ],
            correct_index: 1,
            explanation: "BUG ratings are used by IDA/IES Model Lighting Ordinance (MLO), LEED v4 Light Pollution Reduction credit, and California Title 24 energy code.".into(),
            reference: Some("IESNA TM-15-11, IDA MLO, LEED v4".into()),
        },
        Question {
            id: 6007,
            category: Category::BugRating,
            difficulty: Difficulty::Expert,
            text: "What is the lumen threshold for U0 (zero uplight rating)?".into(),
            options: vec!["< 10 lumens".into(), "< 1 lumen".into(), "0 lumens in both UL and UH zones".into(), "< 50 lumens total uplight".into()],
            correct_index: 2,
            explanation: "U0 requires exactly 0 lumens in both the UL (90-100°) and UH (100-180°) zones — no uplight whatsoever.".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6008,
            category: Category::BugRating,
            difficulty: Difficulty::Expert,
            text: "What gamma angle range defines 'Backlight Very High' (BVH)?".into(),
            options: vec!["60-70° from nadir".into(), "70-80° from nadir".into(), "80-90° from nadir".into(), "90-100° from nadir".into()],
            correct_index: 2,
            explanation: "BVH (Backlight Very High) is the 80-90° zone from nadir, representing near-horizontal light emission behind the luminaire.".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6009,
            category: Category::BugRating,
            difficulty: Difficulty::Intermediate,
            text: "How many angular zones are used in the BUG classification system?".into(),
            options: vec!["3".into(), "5".into(), "8".into(), "12".into()],
            correct_index: 2,
            explanation: "The BUG system divides the hemisphere into 8 zones: FH, FVH, FL, FM (forward), BH, BVH, BL, BM (back), plus UL and UH (uplight).".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6010,
            category: Category::BugRating,
            difficulty: Difficulty::Expert,
            text: "What is the IDA 'Fixture Seal of Approval' maximum uplight requirement?".into(),
            options: vec!["U0 (zero uplight)".into(), "U1 (minimal uplight)".into(), "U2 or less".into(), "No uplight requirement".into()],
            correct_index: 0,
            explanation: "The International Dark-Sky Association (IDA) Fixture Seal of Approval requires U0 — absolutely zero uplight emission.".into(),
            reference: Some("IDA Fixture Seal of Approval criteria".into()),
        },
        Question {
            id: 6011,
            category: Category::BugRating,
            difficulty: Difficulty::Beginner,
            text: "Why are BUG ratings important for outdoor lighting?".into(),
            options: vec![
                "They measure energy efficiency".into(),
                "They quantify light pollution impact and help reduce skyglow".into(),
                "They rate the weatherproofing of the luminaire".into(),
                "They measure the color quality of the light".into(),
            ],
            correct_index: 1,
            explanation: "BUG ratings quantify how much light is wasted (backlight, uplight, glare), directly relating to light pollution, skyglow, and light trespass.".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
        Question {
            id: 6012,
            category: Category::BugRating,
            difficulty: Difficulty::Intermediate,
            text: "What does the Glare (G) component in BUG measure?".into(),
            options: vec![
                "Total luminaire flux".into(),
                "High-angle light intensity that causes disability or discomfort glare".into(),
                "Light reflected from the ground".into(),
                "The color temperature of the light source".into(),
            ],
            correct_index: 1,
            explanation: "The G rating measures intensity in high-angle forward zones (FH: 60-80° and FVH: 80-90°) that can cause glare for drivers and pedestrians.".into(),
            reference: Some("IESNA TM-15-11".into()),
        },
    ]
}
