use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 5001,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Beginner,
            text: "What does LOR stand for?".into(),
            options: vec!["Light Output Ratio".into(), "Luminous Optical Rating".into(), "Light Operating Range".into(), "Lamp Output Rating".into()],
            correct_index: 0,
            explanation: "LOR (Light Output Ratio) is the ratio of total luminous flux emitted by the luminaire to the total flux emitted by the lamp(s).".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 5002,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Beginner,
            text: "What unit is luminous efficacy measured in?".into(),
            options: vec!["cd/m²".into(), "lm/W (lumens per watt)".into(), "W/m²".into(), "cd/klm".into()],
            correct_index: 1,
            explanation: "Luminous efficacy measures how efficiently a light source converts electrical power to visible light, in lumens per watt (lm/W).".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 5003,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Beginner,
            text: "What does DFF stand for?".into(),
            options: vec!["Direct Flux Fraction".into(), "Downward Flux Fraction".into(), "Diffuse Field Factor".into(), "Directional Flux Factor".into()],
            correct_index: 1,
            explanation: "DFF (Downward Flux Fraction) is the percentage of total luminaire flux emitted below the horizontal plane.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 5004,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Intermediate,
            text: "What is the IES definition of beam angle?".into(),
            options: vec![
                "Angle where intensity drops to 10% of maximum".into(),
                "Full angle where intensity \u{2265} 50% of maximum".into(),
                "Half-angle where intensity equals center-beam".into(),
                "Angle containing 90% of total flux".into(),
            ],
            correct_index: 1,
            explanation: "The IES beam angle is the full angle between the two directions where intensity drops to 50% of the maximum intensity value.".into(),
            reference: Some("IESNA Lighting Handbook".into()),
        },
        Question {
            id: 5005,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Intermediate,
            text: "How does the CIE beam angle definition differ from IES?".into(),
            options: vec![
                "CIE uses 10% threshold instead of 50%".into(),
                "CIE references center-beam intensity instead of maximum".into(),
                "CIE uses half-angle instead of full angle".into(),
                "There is no difference".into(),
            ],
            correct_index: 1,
            explanation: "CIE beam angle uses 50% of center-beam (nadir/C0/γ0) intensity, while IES uses 50% of maximum intensity. They differ for batwing distributions where max ≠ center.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 5006,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Intermediate,
            text: "What intensity threshold defines the field angle?".into(),
            options: vec!["50% of maximum".into(), "25% of maximum".into(), "10% of maximum".into(), "5% of maximum".into()],
            correct_index: 2,
            explanation: "The field angle is the full angle where intensity drops to 10% of the maximum (IES) or center-beam (CIE) intensity.".into(),
            reference: Some("IESNA Lighting Handbook".into()),
        },
        Question {
            id: 5007,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Intermediate,
            text: "Are beam and field angles half-angles or full angles?".into(),
            options: vec!["Half-angles".into(), "Full angles".into(), "It depends on the standard".into(), "Quarter-angles".into()],
            correct_index: 1,
            explanation: "Per CIE S 017:2020, both beam and field angles are full angles (the total cone angle, not half). A '30° beam angle' means ±15° from center.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 5008,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Intermediate,
            text: "What does DLOR stand for?".into(),
            options: vec![
                "Direct Light Output Ratio".into(),
                "Downward Light Output Ratio".into(),
                "Distributed Luminous Output Rating".into(),
                "Differential Light Output Ratio".into(),
            ],
            correct_index: 1,
            explanation: "DLOR (Downward Light Output Ratio) is the ratio of downward luminous flux from the luminaire to the total lamp flux. DLOR = LOR × DFF.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 5009,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Expert,
            text: "What are the CIE flux codes N1 through N5?".into(),
            options: vec![
                "N1=efficacy, N2=CRI, N3=CCT, N4=beam angle, N5=field angle".into(),
                "N1=DLOR, N2=0-60° flux, N3=0-40° flux, N4=ULOR, N5=90-120° flux".into(),
                "N1=total flux, N2=peak cd, N3=avg cd, N4=min cd, N5=uniformity".into(),
                "N1=red, N2=green, N3=blue, N4=white, N5=amber percentages".into(),
            ],
            correct_index: 1,
            explanation: "CIE flux codes: N1=DLOR (0-90°), N2=flux in 0-60° zone, N3=flux in 0-40° zone, N4=ULOR (90-180°), N5=flux in 90-120° zone.".into(),
            reference: Some("CIE 102:1993".into()),
        },
        Question {
            id: 5010,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Expert,
            text: "What are the 10 standard room indices used for CU (Coefficient of Utilization) tables?".into(),
            options: vec![
                "1, 2, 3, 4, 5, 6, 7, 8, 9, 10".into(),
                "0.60, 0.80, 1.00, 1.25, 1.50, 2.00, 2.50, 3.00, 4.00, 5.00".into(),
                "0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0".into(),
                "0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0".into(),
            ],
            correct_index: 1,
            explanation: "The standard room index (k) values are: 0.60, 0.80, 1.00, 1.25, 1.50, 2.00, 2.50, 3.00, 4.00, 5.00.".into(),
            reference: Some("CIE 52:1982".into()),
        },
        Question {
            id: 5011,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Beginner,
            text: "What is luminous flux measured in?".into(),
            options: vec!["Candelas (cd)".into(), "Lumens (lm)".into(), "Lux (lx)".into(), "Watts (W)".into()],
            correct_index: 1,
            explanation: "Luminous flux is measured in lumens (lm), representing the total amount of visible light emitted by a source.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 5012,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Intermediate,
            text: "How is luminous intensity related to luminous flux?".into(),
            options: vec![
                "Intensity = Flux × Area".into(),
                "Intensity = Flux / Solid angle (cd = lm/sr)".into(),
                "Intensity = Flux × Distance²".into(),
                "They are independent quantities".into(),
            ],
            correct_index: 1,
            explanation: "Luminous intensity (cd) = luminous flux (lm) per unit solid angle (sr). One candela equals one lumen per steradian.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 5013,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Expert,
            text: "What is the spacing criterion (S/H ratio) used for?".into(),
            options: vec![
                "Calculating beam spread".into(),
                "Determining maximum luminaire spacing for uniform illumination".into(),
                "Measuring lamp socket dimensions".into(),
                "Defining maintenance intervals".into(),
            ],
            correct_index: 1,
            explanation: "The spacing criterion (S/H = Spacing / mounting Height) determines the maximum distance between luminaires to achieve acceptable illuminance uniformity.".into(),
            reference: Some("CIE 52:1982".into()),
        },
        Question {
            id: 5014,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Expert,
            text: "When do IES and CIE beam angles differ significantly?".into(),
            options: vec![
                "For narrow spot lights".into(),
                "For batwing distributions where center-beam < maximum intensity".into(),
                "For uplights".into(),
                "They never differ significantly".into(),
            ],
            correct_index: 1,
            explanation: "For batwing distributions, the maximum intensity occurs off-axis (not at center/nadir), so 50% of max ≠ 50% of center-beam, giving different beam angles.".into(),
            reference: Some("CIE S 017:2020, IESNA Lighting Handbook".into()),
        },
        Question {
            id: 5015,
            category: Category::PhotometricCalc,
            difficulty: Difficulty::Beginner,
            text: "What is the inverse square law in photometry?".into(),
            options: vec![
                "Illuminance = Intensity / Distance²".into(),
                "Intensity = Flux × Distance²".into(),
                "Flux = Illuminance × Distance".into(),
                "Illuminance = Flux / Area²".into(),
            ],
            correct_index: 0,
            explanation: "The inverse square law states that illuminance (E) = luminous intensity (I) / distance² (d²). Doubling the distance reduces illuminance by 4x.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
    ]
}
