use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 8001,
            category: Category::ColorScience,
            difficulty: Difficulty::Beginner,
            text: "What unit is color temperature measured in?".into(),
            options: vec!["Celsius (°C)".into(), "Kelvin (K)".into(), "Fahrenheit (°F)".into(), "Nanometers (nm)".into()],
            correct_index: 1,
            explanation: "Correlated Color Temperature (CCT) is measured in Kelvin (K).".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 8002,
            category: Category::ColorScience,
            difficulty: Difficulty::Beginner,
            text: "Is 2700K considered warm or cool light?".into(),
            options: vec!["Cool (bluish)".into(), "Warm (yellowish/incandescent-like)".into(), "Neutral".into(), "Daylight".into()],
            correct_index: 1,
            explanation: "2700K is warm white light, similar to traditional incandescent bulbs. Lower Kelvin = warmer color. 5000K+ = cool/daylight.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 8003,
            category: Category::ColorScience,
            difficulty: Difficulty::Beginner,
            text: "What does CRI stand for?".into(),
            options: vec!["Color Rendering Index".into(), "Chromatic Reference Indicator".into(), "Color Reproduction Intensity".into(), "Calibrated Rendering Instrument".into()],
            correct_index: 0,
            explanation: "CRI (Color Rendering Index) measures how accurately a light source renders colors compared to a reference illuminant.".into(),
            reference: Some("CIE 13.3:1995".into()),
        },
        Question {
            id: 8004,
            category: Category::ColorScience,
            difficulty: Difficulty::Intermediate,
            text: "What CRI group in EULUMDAT has Ra \u{2265} 90?".into(),
            options: vec!["Group 1A".into(), "Group 1B".into(), "Group 2A".into(), "Group 3".into()],
            correct_index: 0,
            explanation: "CRI Group 1A represents Ra \u{2265} 90, the highest color rendering quality. 1B = 80-89, 2A = 70-79, 2B = 60-69.".into(),
            reference: Some("EULUMDAT specification".into()),
        },
        Question {
            id: 8005,
            category: Category::ColorScience,
            difficulty: Difficulty::Intermediate,
            text: "What does TM-30 Rf measure?".into(),
            options: vec![
                "Color temperature accuracy".into(),
                "Fidelity (color accuracy, 0-100)".into(),
                "Gamut (color saturation)".into(),
                "Flicker frequency".into(),
            ],
            correct_index: 1,
            explanation: "TM-30 Rf (Fidelity Index) measures color accuracy on a 0-100 scale, similar to CRI Ra but using 99 color evaluation samples instead of 8.".into(),
            reference: Some("IES TM-30-20".into()),
        },
        Question {
            id: 8006,
            category: Category::ColorScience,
            difficulty: Difficulty::Intermediate,
            text: "What does TM-30 Rg measure?".into(),
            options: vec![
                "Color fidelity".into(),
                "Gamut (color saturation, 60-140, 100=reference)".into(),
                "Glare rating".into(),
                "Green light output".into(),
            ],
            correct_index: 1,
            explanation: "TM-30 Rg (Gamut Index) measures color saturation: 100 = same as reference, >100 = increased saturation, <100 = desaturated.".into(),
            reference: Some("IES TM-30-20".into()),
        },
        Question {
            id: 8007,
            category: Category::ColorScience,
            difficulty: Difficulty::Expert,
            text: "What does a positive Duv value mean?".into(),
            options: vec![
                "Pinkish tint (below Planckian locus)".into(),
                "Greenish tint (above Planckian locus)".into(),
                "Perfect white light".into(),
                "High CRI value".into(),
            ],
            correct_index: 1,
            explanation: "Positive Duv indicates the chromaticity is above the Planckian (blackbody) locus, giving a greenish tint. Negative Duv = pinkish/rosy tint.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 8008,
            category: Category::ColorScience,
            difficulty: Difficulty::Expert,
            text: "Why is R9 (deep red rendering) reported separately from CRI Ra?".into(),
            options: vec![
                "R9 is not part of the CRI standard".into(),
                "Deep red rendering is critical but averaged out in the Ra calculation".into(),
                "R9 measures a different physical property".into(),
                "R9 is only relevant for horticultural lighting".into(),
            ],
            correct_index: 1,
            explanation: "CRI Ra averages 8 pastel test colors (R1-R8). Deep red (R9) is critical for skin tones, food, and art but is averaged out. Many LEDs have poor R9 despite high Ra.".into(),
            reference: Some("CIE 13.3:1995".into()),
        },
        Question {
            id: 8009,
            category: Category::ColorScience,
            difficulty: Difficulty::Intermediate,
            text: "What CCT range is considered 'neutral white'?".into(),
            options: vec!["2200-2700K".into(), "3000-3500K".into(), "3500-4500K".into(), "5000-6500K".into()],
            correct_index: 2,
            explanation: "Neutral white is approximately 3500-4500K. Below 3500K is warm white, above 4500-5000K is cool white/daylight.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 8010,
            category: Category::ColorScience,
            difficulty: Difficulty::Expert,
            text: "What is the maximum achievable CRI (Ra) value?".into(),
            options: vec!["95".into(), "99".into(), "100".into(), "There is no maximum".into()],
            correct_index: 2,
            explanation: "CRI Ra ranges from 0 to 100, where 100 means perfect color rendering identical to the reference illuminant.".into(),
            reference: Some("CIE 13.3:1995".into()),
        },
        Question {
            id: 8011,
            category: Category::ColorScience,
            difficulty: Difficulty::Beginner,
            text: "What approximate CCT does typical daylight have?".into(),
            options: vec!["2700K".into(), "3500K".into(), "5600K".into(), "8000K".into()],
            correct_index: 2,
            explanation: "Standard daylight (CIE Illuminant D55/D65) has a CCT of approximately 5500-6500K.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 8012,
            category: Category::ColorScience,
            difficulty: Difficulty::Intermediate,
            text: "What does SPD stand for in color science?".into(),
            options: vec![
                "Standard Power Distribution".into(),
                "Spectral Power Distribution".into(),
                "Source Power Density".into(),
                "Spectral Photometric Data".into(),
            ],
            correct_index: 1,
            explanation: "SPD (Spectral Power Distribution) describes the power emitted by a light source at each wavelength across the visible spectrum.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
    ]
}
