use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 4001,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Beginner,
            text: "What does gamma = 0° represent in photometric coordinate systems?".into(),
            options: vec!["Zenith (straight up)".into(), "Nadir (straight down)".into(), "Horizontal".into(), "Front of luminaire".into()],
            correct_index: 1,
            explanation: "Gamma = 0° is nadir, meaning straight down from the luminaire. This is the reference direction for Type C photometry.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 4002,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Beginner,
            text: "What does gamma = 90° represent?".into(),
            options: vec!["Nadir".into(), "Zenith".into(), "Horizontal".into(), "45° below horizontal".into()],
            correct_index: 2,
            explanation: "Gamma = 90° is the horizontal plane, perpendicular to the vertical axis of the luminaire.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 4003,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Beginner,
            text: "What does C = 0° represent?".into(),
            options: vec!["Left side of luminaire".into(), "Right side of luminaire".into(), "Front of luminaire".into(), "Top of luminaire".into()],
            correct_index: 2,
            explanation: "C = 0° is defined as the front of the luminaire. C-planes rotate around the vertical axis: C90° is right, C180° is back, C270° is left.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 4004,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Intermediate,
            text: "What is the gamma angle at zenith (straight up)?".into(),
            options: vec!["0°".into(), "90°".into(), "180°".into(), "270°".into()],
            correct_index: 2,
            explanation: "Gamma = 180° is zenith (straight up). The gamma angle is measured from nadir (0°) through horizontal (90°) to zenith (180°).".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 4005,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Intermediate,
            text: "In Type C photometry, what direction does C = 180° point?".into(),
            options: vec!["Front".into(), "Right side".into(), "Back".into(), "Left side".into()],
            correct_index: 2,
            explanation: "C = 180° points to the back of the luminaire. The C-plane system goes: 0° front, 90° right, 180° back, 270° left.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 4006,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Intermediate,
            text: "Which photometric type uses horizontal and vertical angles instead of C-planes and gamma?".into(),
            options: vec!["Type A".into(), "Type B".into(), "Type C".into(), "Both A and B".into()],
            correct_index: 1,
            explanation: "Type B photometry uses horizontal (H) and vertical (V) angles, commonly for floodlights. Type C uses C-plane and gamma angles.".into(),
            reference: Some("ANSI/IESNA LM-63".into()),
        },
        Question {
            id: 4007,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Expert,
            text: "What transformation converts Type B (H,V) angles to Type C (C,γ)?".into(),
            options: vec![
                "C = H, γ = V (direct mapping)".into(),
                "γ = arccos(cos(V)·cos(H)), C = atan2(sin(H), sin(V)·cos(H))".into(),
                "C = V + 90°, γ = H".into(),
                "No mathematical conversion exists".into(),
            ],
            correct_index: 1,
            explanation: "The conversion uses spherical trigonometry: γ = arccos(cos(V)·cos(H)) and C = atan2(sin(H), sin(V)·cos(H)).".into(),
            reference: Some("CIE 102:1993".into()),
        },
        Question {
            id: 4008,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Expert,
            text: "What is the 'photometric center' of a luminaire?".into(),
            options: vec![
                "The geometric center of the housing".into(),
                "The point from which photometric angles are measured".into(),
                "The brightest point on the luminaire surface".into(),
                "The center of the light source (lamp)".into(),
            ],
            correct_index: 1,
            explanation: "The photometric center is the origin point from which all angular measurements (C-plane and gamma) are referenced. It may differ from the geometric center.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 4009,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Beginner,
            text: "How many degrees make a full rotation around C-planes?".into(),
            options: vec!["90°".into(), "180°".into(), "270°".into(), "360°".into()],
            correct_index: 3,
            explanation: "C-planes form a full 360° rotation around the vertical axis of the luminaire.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
        Question {
            id: 4010,
            category: Category::CoordinateSystems,
            difficulty: Difficulty::Intermediate,
            text: "What is the typical gamma angle range for a downlight?".into(),
            options: vec!["0° to 90°".into(), "0° to 180°".into(), "90° to 180°".into(), "0° to 360°".into()],
            correct_index: 0,
            explanation: "Downlights emit light primarily in the lower hemisphere (0° to 90° from nadir), so their significant intensity data is in this gamma range.".into(),
            reference: Some("CIE S 017:2020".into()),
        },
    ]
}
