use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 9001,
            category: Category::Horticultural,
            difficulty: Difficulty::Beginner,
            text: "What wavelength range defines PAR (Photosynthetically Active Radiation)?".into(),
            options: vec!["200-400nm".into(), "400-700nm".into(), "300-800nm".into(), "500-600nm".into()],
            correct_index: 1,
            explanation: "PAR is defined as radiation in the 400-700nm wavelength range, which plants use for photosynthesis.".into(),
            reference: Some("ASABE S640".into()),
        },
        Question {
            id: 9002,
            category: Category::Horticultural,
            difficulty: Difficulty::Beginner,
            text: "What unit is PPFD measured in?".into(),
            options: vec!["lm/m²".into(), "W/m²".into(), "\u{00b5}mol/(m\u{00b2}\u{00b7}s)".into(), "cd/m²".into()],
            correct_index: 2,
            explanation: "PPFD (Photosynthetic Photon Flux Density) is measured in micromoles per square meter per second (\u{00b5}mol/m\u{00b2}/s).".into(),
            reference: Some("ASABE S640".into()),
        },
        Question {
            id: 9003,
            category: Category::Horticultural,
            difficulty: Difficulty::Beginner,
            text: "What does PPF stand for?".into(),
            options: vec![
                "Photometric Power Factor".into(),
                "Photosynthetic Photon Flux".into(),
                "Peak Power Frequency".into(),
                "Plant Protection Factor".into(),
            ],
            correct_index: 1,
            explanation: "PPF (Photosynthetic Photon Flux) measures the total number of photons in the 400-700nm range emitted per second, in \u{00b5}mol/s.".into(),
            reference: Some("ASABE S640".into()),
        },
        Question {
            id: 9004,
            category: Category::Horticultural,
            difficulty: Difficulty::Intermediate,
            text: "What spectral zone (wavelength range) primarily promotes flowering in plants?".into(),
            options: vec!["Blue (400-500nm)".into(), "Green (500-600nm)".into(), "Red (600-700nm)".into(), "Far-red (700-800nm)".into()],
            correct_index: 2,
            explanation: "Red light (600-700nm) is the primary driver of photosynthesis and flowering. Chlorophyll a has peak absorption around 660nm.".into(),
            reference: Some("IES TM-33-23".into()),
        },
        Question {
            id: 9005,
            category: Category::Horticultural,
            difficulty: Difficulty::Intermediate,
            text: "What does the R:FR (Red to Far-Red) ratio control in plants?".into(),
            options: vec![
                "Leaf color (green vs red)".into(),
                "Morphology — high R:FR = compact, low R:FR = elongated".into(),
                "Root growth speed".into(),
                "Fruit sugar content".into(),
            ],
            correct_index: 1,
            explanation: "The R:FR ratio controls phytochrome response: high R:FR promotes compact growth, low R:FR triggers shade-avoidance (elongation, reduced branching).".into(),
            reference: Some("IES TM-33-23".into()),
        },
        Question {
            id: 9006,
            category: Category::Horticultural,
            difficulty: Difficulty::Expert,
            text: "What is DLI and what are typical values for seedlings?".into(),
            options: vec![
                "Daily Light Integral, 0.5-1 mol/m\u{00b2}/day".into(),
                "Daily Light Integral, 3-6 mol/m\u{00b2}/day".into(),
                "Direct Light Intensity, 100-200 lux".into(),
                "Diurnal Luminance Index, 50-100 cd/m\u{00b2}".into(),
            ],
            correct_index: 1,
            explanation: "DLI (Daily Light Integral) is the total photosynthetic light received per day, in mol/m\u{00b2}/day. Seedlings need 3-6, flowering plants need 14-25.".into(),
            reference: Some("IES TM-33-23".into()),
        },
        Question {
            id: 9007,
            category: Category::Horticultural,
            difficulty: Difficulty::Intermediate,
            text: "What does blue light (400-500nm) primarily promote in plants?".into(),
            options: vec![
                "Flowering and fruiting".into(),
                "Root development".into(),
                "Vegetative growth, leaf expansion, and stomatal opening".into(),
                "Seed germination".into(),
            ],
            correct_index: 2,
            explanation: "Blue light promotes vegetative growth, leaf expansion, stomatal opening, and phototropism (directional growth toward light).".into(),
            reference: Some("IES TM-33-23".into()),
        },
        Question {
            id: 9008,
            category: Category::Horticultural,
            difficulty: Difficulty::Expert,
            text: "What is the photon efficacy unit used to rate horticultural luminaires?".into(),
            options: vec!["lm/W".into(), "\u{00b5}mol/J (\u{00b5}mol/s per watt)".into(), "W/nm".into(), "cd/W".into()],
            correct_index: 1,
            explanation: "Horticultural luminaire efficacy is measured in \u{00b5}mol/J (micromoles per joule), or equivalently \u{00b5}mol/s per watt. Top LEDs reach 3.0+ \u{00b5}mol/J.".into(),
            reference: Some("ASABE S640, DLC Horticultural QPL".into()),
        },
        Question {
            id: 9009,
            category: Category::Horticultural,
            difficulty: Difficulty::Beginner,
            text: "Why can't standard lumens (lm) be used to measure horticultural light?".into(),
            options: vec![
                "Lumens are too imprecise".into(),
                "Lumens weight the human visual response, not photosynthetic response".into(),
                "Lumens don't measure visible light".into(),
                "Plants only use infrared light".into(),
            ],
            correct_index: 1,
            explanation: "Lumens use the V(\u{03bb}) human eye sensitivity curve, which peaks at 555nm (green). Plants use all PAR wavelengths (400-700nm) roughly equally, so photon counts (\u{00b5}mol) are more relevant.".into(),
            reference: Some("ASABE S640".into()),
        },
        Question {
            id: 9010,
            category: Category::Horticultural,
            difficulty: Difficulty::Expert,
            text: "What role does UV-A (315-400nm) play in horticultural lighting?".into(),
            options: vec![
                "No effect on plants".into(),
                "Promotes photosynthesis efficiency".into(),
                "Stimulates secondary metabolites (flavonoids, anthocyanins) for pest/UV defense".into(),
                "Primarily used for sterilization".into(),
            ],
            correct_index: 2,
            explanation: "UV-A stimulates production of secondary metabolites like flavonoids and anthocyanins, which act as UV protection and pest deterrents, and can enhance flavor/color.".into(),
            reference: Some("IES TM-33-23".into()),
        },
    ]
}
