use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 11001,
            category: Category::ModernFormats,
            difficulty: Difficulty::Beginner,
            text: "What limitation do traditional LDT and IES formats share?".into(),
            options: vec![
                "They cannot store intensity data".into(),
                "They cannot store spectral power distribution (SPD) data".into(),
                "They are not machine-readable".into(),
                "They can only store one C-plane".into(),
            ],
            correct_index: 1,
            explanation: "Neither LDT nor IES can store full spectral power distribution data — they only carry photometric (intensity) and basic color info (CCT, CRI group).".into(),
            reference: Some("IES TM-33-23".into()),
        },
        Question {
            id: 11002,
            category: Category::ModernFormats,
            difficulty: Difficulty::Intermediate,
            text: "What format standards are equivalent to IES TM-33?".into(),
            options: vec![
                "EULUMDAT and CIE 102".into(),
                "ATLA S001 and UNI 11733".into(),
                "GLDF and ROLF".into(),
                "EN 13032 and ISO 10527".into(),
            ],
            correct_index: 1,
            explanation: "IES TM-33-23, ATLA S001, and UNI 11733 are equivalent standards defining the same XML-based photometric data format.".into(),
            reference: Some("IES TM-33-23, ATLA S001".into()),
        },
        Question {
            id: 11003,
            category: Category::ModernFormats,
            difficulty: Difficulty::Intermediate,
            text: "What key data type does TM-33 support that LDT/IES cannot?".into(),
            options: vec![
                "Multiple luminaire configurations".into(),
                "Full spectral power distribution (SPD)".into(),
                "3D luminaire geometry".into(),
                "Installation instructions".into(),
            ],
            correct_index: 1,
            explanation: "TM-33's major advantage is native support for spectral power distribution data, enabling color science calculations directly from the file.".into(),
            reference: Some("IES TM-33-23".into()),
        },
        Question {
            id: 11004,
            category: Category::ModernFormats,
            difficulty: Difficulty::Expert,
            text: "How much smaller are TM-33 JSON files compared to equivalent XML?".into(),
            options: vec!["~10% smaller".into(), "~50% smaller".into(), "~90% smaller".into(), "Same size".into()],
            correct_index: 2,
            explanation: "TM-33 JSON encoding is approximately 90% smaller than XML, primarily because it eliminates verbose XML tags and uses compact array notation for intensity data.".into(),
            reference: Some("IES TM-33-23".into()),
        },
        Question {
            id: 11005,
            category: Category::ModernFormats,
            difficulty: Difficulty::Intermediate,
            text: "What serialization formats does TM-33 support?".into(),
            options: vec![
                "Only XML".into(),
                "XML and JSON".into(),
                "XML, JSON, and YAML".into(),
                "Only JSON".into(),
            ],
            correct_index: 1,
            explanation: "TM-33 defines both XML and JSON serializations, with XML being the canonical format and JSON being a compact alternative.".into(),
            reference: Some("IES TM-33-23".into()),
        },
        Question {
            id: 11006,
            category: Category::ModernFormats,
            difficulty: Difficulty::Expert,
            text: "What is GLDF (Global Lighting Data Format)?".into(),
            options: vec![
                "A new photometric file format replacing IES".into(),
                "A container format for luminaire product data including photometry, geometry, and metadata".into(),
                "A color management standard".into(),
                "A BIM file format".into(),
            ],
            correct_index: 1,
            explanation: "GLDF is a comprehensive container format that bundles photometric data (LDT/IES/TM-33), 3D geometry, product metadata, and variant configurations.".into(),
            reference: Some("GLDF specification".into()),
        },
        Question {
            id: 11007,
            category: Category::ModernFormats,
            difficulty: Difficulty::Beginner,
            text: "Which of these is NOT a photometric data file format?".into(),
            options: vec![".ldt (EULUMDAT)".into(), ".ies (IESNA)".into(), ".dwg (AutoCAD)".into(), "TM-33 XML".into()],
            correct_index: 2,
            explanation: ".dwg is an AutoCAD drawing file format, not a photometric data format. LDT, IES, and TM-33 XML all store photometric intensity distributions.".into(),
            reference: None,
        },
        Question {
            id: 11008,
            category: Category::ModernFormats,
            difficulty: Difficulty::Expert,
            text: "What horticultural data can TM-33 store that LDT/IES cannot?".into(),
            options: vec![
                "Plant growth rates".into(),
                "Per-wavelength spectral data enabling PAR/PPF/PPFD calculations".into(),
                "Soil moisture requirements".into(),
                "Fertilizer recommendations".into(),
            ],
            correct_index: 1,
            explanation: "TM-33's spectral data support enables calculating horticultural metrics (PAR, PPF, PPFD, DLI, R:FR ratio) directly from the file data.".into(),
            reference: Some("IES TM-33-23".into()),
        },
    ]
}
