use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 15001,
            category: Category::Standards,
            difficulty: Difficulty::Beginner,
            text: "What does CIE stand for?".into(),
            options: vec![
                "Committee for Illumination Engineering".into(),
                "Commission Internationale de l'Éclairage (International Commission on Illumination)".into(),
                "Certified Illumination Expert".into(),
                "Center for Industrial Electrics".into(),
            ],
            correct_index: 1,
            explanation: "CIE stands for Commission Internationale de l'Éclairage, the International Commission on Illumination — the global authority on light and color science.".into(),
            reference: Some("CIE".into()),
        },
        Question {
            id: 15002,
            category: Category::Standards,
            difficulty: Difficulty::Beginner,
            text: "What European standard covers indoor workplace lighting?".into(),
            options: vec!["EN 13201".into(), "EN 12464-1".into(), "EN 15193".into(), "EN 62722".into()],
            correct_index: 1,
            explanation: "EN 12464-1 specifies lighting requirements for indoor work places, including illuminance levels, uniformity, UGR limits, and color rendering.".into(),
            reference: Some("EN 12464-1".into()),
        },
        Question {
            id: 15003,
            category: Category::Standards,
            difficulty: Difficulty::Intermediate,
            text: "What does EN 13201 cover?".into(),
            options: vec!["Indoor lighting".into(), "Road and street lighting".into(), "Emergency lighting".into(), "Sports lighting".into()],
            correct_index: 1,
            explanation: "EN 13201 is the European standard for road lighting, defining lighting classes (M, C, P, S, A, ES, EV) and performance requirements.".into(),
            reference: Some("EN 13201".into()),
        },
        Question {
            id: 15004,
            category: Category::Standards,
            difficulty: Difficulty::Intermediate,
            text: "What is IDA in the context of lighting?".into(),
            options: vec![
                "International Design Association".into(),
                "International Dark-Sky Association".into(),
                "Indoor Design Authority".into(),
                "Illumination Data Archive".into(),
            ],
            correct_index: 1,
            explanation: "IDA (International Dark-Sky Association) promotes responsible outdoor lighting to minimize light pollution, glare, and impacts on wildlife.".into(),
            reference: Some("IDA".into()),
        },
        Question {
            id: 15005,
            category: Category::Standards,
            difficulty: Difficulty::Intermediate,
            text: "What lighting credit does LEED v4 offer?".into(),
            options: vec![
                "Energy Star certification".into(),
                "Light Pollution Reduction credit".into(),
                "Daylight Optimization credit".into(),
                "Smart Lighting credit".into(),
            ],
            correct_index: 1,
            explanation: "LEED v4 includes a 'Light Pollution Reduction' credit (SS Credit) that uses BUG ratings to evaluate exterior lighting's environmental impact.".into(),
            reference: Some("LEED v4, USGBC".into()),
        },
        Question {
            id: 15006,
            category: Category::Standards,
            difficulty: Difficulty::Expert,
            text: "What does California Title 24 require for outdoor lighting?".into(),
            options: vec![
                "Only LED sources".into(),
                "BUG-rated luminaires meeting maximum allowable ratings per lighting zone".into(),
                "Motion sensors on all fixtures".into(),
                "Solar-powered lighting only".into(),
            ],
            correct_index: 1,
            explanation: "California Title 24 (Energy Code) requires outdoor luminaires to have BUG ratings that don't exceed maximum allowable values for the applicable lighting zone (LZ0-LZ4).".into(),
            reference: Some("California Title 24, Part 6".into()),
        },
        Question {
            id: 15007,
            category: Category::Standards,
            difficulty: Difficulty::Beginner,
            text: "What does NEMA stand for?".into(),
            options: vec![
                "National Energy Management Authority".into(),
                "National Electrical Manufacturers Association".into(),
                "National Emergency Monitoring Agency".into(),
                "North European Measurement Association".into(),
            ],
            correct_index: 1,
            explanation: "NEMA stands for National Electrical Manufacturers Association, which publishes standards for electrical equipment including lighting.".into(),
            reference: Some("NEMA".into()),
        },
        Question {
            id: 15008,
            category: Category::Standards,
            difficulty: Difficulty::Expert,
            text: "What are the lighting zones defined in the IES/IDA MLO?".into(),
            options: vec![
                "Zones A through F".into(),
                "LZ0 (no ambient), LZ1 (low), LZ2 (moderate), LZ3 (moderately high), LZ4 (high)".into(),
                "Indoor and outdoor only".into(),
                "Residential, commercial, industrial".into(),
            ],
            correct_index: 1,
            explanation: "The Model Lighting Ordinance defines 5 zones: LZ0 (wilderness/protected), LZ1 (rural/low), LZ2 (suburban/moderate), LZ3 (urban/moderately high), LZ4 (high-activity commercial).".into(),
            reference: Some("IDA/IES Model Lighting Ordinance".into()),
        },
        Question {
            id: 15009,
            category: Category::Standards,
            difficulty: Difficulty::Intermediate,
            text: "What does CIE 102 address?".into(),
            options: vec![
                "Color rendering measurement".into(),
                "Recommended practice for photometric data transfer".into(),
                "Glare rating calculation".into(),
                "Daylight simulation methods".into(),
            ],
            correct_index: 1,
            explanation: "CIE 102:1993 'Recommended File Format for the Electronic Transfer of Luminaire Photometric Data' defines conventions for presenting photometric diagrams.".into(),
            reference: Some("CIE 102:1993".into()),
        },
        Question {
            id: 15010,
            category: Category::Standards,
            difficulty: Difficulty::Expert,
            text: "What is the relationship between ISO 8995 and EN 12464?".into(),
            options: vec![
                "They are unrelated standards".into(),
                "ISO 8995 and EN 12464-1 are harmonized international/European standards for workplace lighting".into(),
                "ISO 8995 supersedes EN 12464".into(),
                "EN 12464 covers outdoor; ISO 8995 covers indoor".into(),
            ],
            correct_index: 1,
            explanation: "ISO 8995 (CIE S 008) and EN 12464-1 are harmonized standards covering indoor workplace lighting requirements, with EN 12464-1 being the European implementation.".into(),
            reference: Some("ISO 8995, EN 12464-1".into()),
        },
    ]
}
