use crate::{Category, Difficulty, Question};

pub fn questions() -> Vec<Question> {
    vec![
        Question {
            id: 7001,
            category: Category::UgrGlare,
            difficulty: Difficulty::Beginner,
            text: "What does UGR stand for?".into(),
            options: vec!["Universal Glare Rating".into(), "Unified Glare Rating".into(), "Uniform Glare Ratio".into(), "Unit Glare Reference".into()],
            correct_index: 1,
            explanation: "UGR stands for Unified Glare Rating, a measure of discomfort glare from luminaires in indoor environments.".into(),
            reference: Some("CIE 117:1995".into()),
        },
        Question {
            id: 7002,
            category: Category::UgrGlare,
            difficulty: Difficulty::Beginner,
            text: "Is a higher or lower UGR value desirable?".into(),
            options: vec!["Higher is better".into(), "Lower is better (less glare)".into(), "UGR = 19 is always optimal".into(), "It depends on room size".into()],
            correct_index: 1,
            explanation: "Lower UGR values indicate less discomfort glare. Typical limits: offices \u{2264}19, corridors \u{2264}25, detailed work \u{2264}16.".into(),
            reference: Some("CIE 117:1995, EN 12464-1".into()),
        },
        Question {
            id: 7003,
            category: Category::UgrGlare,
            difficulty: Difficulty::Intermediate,
            text: "What is the typical UGR limit for office environments?".into(),
            options: vec!["\u{2264} 13".into(), "\u{2264} 16".into(), "\u{2264} 19".into(), "\u{2264} 25".into()],
            correct_index: 2,
            explanation: "EN 12464-1 specifies UGR \u{2264} 19 for general offices. More demanding tasks like technical drawing require \u{2264} 16.".into(),
            reference: Some("EN 12464-1".into()),
        },
        Question {
            id: 7004,
            category: Category::UgrGlare,
            difficulty: Difficulty::Intermediate,
            text: "What factors does the UGR formula consider?".into(),
            options: vec![
                "Only luminaire brightness and room reflectances".into(),
                "Luminance of the luminaire, solid angle, position index, and background luminance".into(),
                "Only the beam angle and mounting height".into(),
                "Only the total luminous flux and room dimensions".into(),
            ],
            correct_index: 1,
            explanation: "UGR = 8 × log\u{2081}\u{2080}((0.25/L\u{2095}) \u{00d7} \u{03a3}(L\u{00b2}\u{00d7}\u{03c9}/p\u{00b2})) — considering luminaire luminance (L), solid angle (\u{03c9}), position index (p), and background luminance (L\u{2095}).".into(),
            reference: Some("CIE 117:1995".into()),
        },
        Question {
            id: 7005,
            category: Category::UgrGlare,
            difficulty: Difficulty::Expert,
            text: "What is the UGR formula?".into(),
            options: vec![
                "UGR = L × \u{03c9} / p".into(),
                "UGR = 8 × log\u{2081}\u{2080}((0.25/L\u{2095}) × \u{03a3}(L²×\u{03c9}/p²))".into(),
                "UGR = 10 × log\u{2081}\u{2080}(L/L\u{2095})".into(),
                "UGR = (L × A) / (d² × p)".into(),
            ],
            correct_index: 1,
            explanation: "The UGR formula is UGR = 8 × log\u{2081}\u{2080}((0.25/L\u{2095}) × \u{03a3}(L²×\u{03c9}/p²)), where L\u{2095} is background luminance, L is source luminance, \u{03c9} is solid angle, and p is position index.".into(),
            reference: Some("CIE 117:1995".into()),
        },
        Question {
            id: 7006,
            category: Category::UgrGlare,
            difficulty: Difficulty::Expert,
            text: "What standard room dimensions are used for UGR table calculations?".into(),
            options: vec![
                "Always 3m × 3m × 3m".into(),
                "Standardized X/Y ratios with mounting height, per CIE 190:2010".into(),
                "Any room dimensions the designer specifies".into(),
                "10m × 10m × 3m only".into(),
            ],
            correct_index: 1,
            explanation: "CIE 190:2010 defines standard room dimensions as ratios of X/H and Y/H (room dimensions to mounting height) for UGR table generation.".into(),
            reference: Some("CIE 190:2010".into()),
        },
        Question {
            id: 7007,
            category: Category::UgrGlare,
            difficulty: Difficulty::Intermediate,
            text: "What does 'position index' (p) represent in the UGR formula?".into(),
            options: vec![
                "The luminaire's position in the ceiling grid".into(),
                "The displacement of the luminaire from the observer's line of sight".into(),
                "The height of the luminaire above the floor".into(),
                "The distance between adjacent luminaires".into(),
            ],
            correct_index: 1,
            explanation: "The position index accounts for how far the glare source is displaced from the observer's direct line of sight. Sources directly ahead have lower p values (more glare).".into(),
            reference: Some("CIE 117:1995".into()),
        },
        Question {
            id: 7008,
            category: Category::UgrGlare,
            difficulty: Difficulty::Beginner,
            text: "What standard defines UGR?".into(),
            options: vec!["CIE 117:1995".into(), "IESNA TM-15-11".into(), "EN 13201".into(), "ISO 8995".into()],
            correct_index: 0,
            explanation: "UGR was defined by CIE Technical Report 117:1995 'Discomfort Glare in Interior Lighting'.".into(),
            reference: Some("CIE 117:1995".into()),
        },
        Question {
            id: 7009,
            category: Category::UgrGlare,
            difficulty: Difficulty::Expert,
            text: "What is the UGR step size used in standard specifications?".into(),
            options: vec!["1 unit".into(), "2 units".into(), "3 units".into(), "5 units".into()],
            correct_index: 2,
            explanation: "UGR values are specified in steps of 3: 10, 13, 16, 19, 22, 25, 28. A 3-unit change is considered the minimum noticeable difference.".into(),
            reference: Some("CIE 117:1995".into()),
        },
        Question {
            id: 7010,
            category: Category::UgrGlare,
            difficulty: Difficulty::Intermediate,
            text: "What UGR limit is typical for corridors and hallways?".into(),
            options: vec!["\u{2264} 16".into(), "\u{2264} 19".into(), "\u{2264} 22".into(), "\u{2264} 25".into()],
            correct_index: 3,
            explanation: "Corridors and circulation areas have a relaxed UGR limit of \u{2264}25 since people are moving through rather than performing sustained visual tasks.".into(),
            reference: Some("EN 12464-1".into()),
        },
    ]
}
